feat: simulate images
feat: upload PictureCreation folder and rename

defined a bunch of variables and made the script for circles

target generator is done

I pulled an all-nighter for this... just to make fucking pictures

leftover

fixed a couple of things

new master images* (the files are too big)

the thing is that we are dealing with a 1GB photo and most likely will take a while to generate all the background images using flip image augmentation

Im going insane

for some reason whenever I try to use opencv's bounding box it always throws this error: cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::convexHull'

IDK what this means and its 2 am and I just want this to work

final a some what working script

whats left: figure out how to get a more accurate bounding box, how to crop a rotated rectangle

updated ignores

finally creates the images with all features

but the image of the picture is bad quality due to all the rotating so im going to rewrite it. Also, the coordinates for the bounding box is not right for some reason.

alright the valid camera image generation

basically fixed the transformations

end of me testing stuff

All I have done testenv has like what the script really should be.

changed some coords

ayo no rotation it works so far

It works. It accurately represents the runway

finally finished ( to use import pain and run fnl_valid_gen)

cleaning the branch up and switched to jpgs bc smaller

added a test

initial exploration and math

i am god

check if target in snapshot

data saving done

change imports and use of var

curse you advik the platypus!!!!!!!!!

I rewrote the whole thing again

fix some file logic

ran some tests and entered stats

word and decimal points

remove notebook